# -*- coding: utf-8 -*-
"""
Analyse Data:
    Library for processing the sequences generated by the quantum computers (QCs)
    to analyze their randomness properties. Specifically, it is used to:
        - Estimate the min-entropy (Hmin) and, if possible, the total entropy.

        - Perform the selected statistical tests (determine whether NIST alone is sufficient
          or whether Dieharder should also be used).
        - Perform second-order tests (tests applied to the results of the statistical tests),
          following Shen's approach.

    The results will be stored in text files associated with each quantum computer,
    appending them to any existing data in those files.
"""
#%% Librerias
import numpy as np
import os as os
import WriteFile as WF
import tqdm as tqdm

# Tests NIST (by stevenang: https://github.com/stevenang/randomness_testsuite)
from NIST.ApproximateEntropy import ApproximateEntropy as aet
from NIST.Complexity import ComplexityTest as ct
from NIST.CumulativeSum import CumulativeSums as cst
from NIST.FrequencyTest import FrequencyTest as ft
from NIST.RandomExcursions import RandomExcursions as ret
from NIST.RunTest import RunTest as rt
from NIST.Spectral import SpectralTest as st
from NIST.Universal import Universal as ut
import NIST.BinaryMatrix as bm

# For Kolmogorov Complexity estimations
import gzip as gzip # Compresor de Huffmann https://docs.python.org/3/library/gzip.html
import lzip as lzip # Compresor de Cadenas de Markov https://www.nongnu.org/lzip/
import pyppmd as ppm # Compresor PPM https://pyppmd.readthedocs.io/en/latest/api_guide.html

from uncertainties import ufloat
#%% Global Variables
readStep = 10**6 # N of bytes for each read order
epsilon = 0.01 # Tolerance of tests
#%% Functions

#%%% Plots
def Axe_Canvas(n,cost,ax, linesNames = [], multipleLines = False):
    ax.set_xlabel("n Bits")
    ax.set_ylabel("Cost ($)")
    ax.grid()
    if multipleLines:
        nLines = len(n)
        if len(linesNames) == 0:
            linesNames = [f"Line {i+1}" for i in range(nLines)]
        for i in range(nLines):
            ax.plot(n[i], cost[i], label = linesNames[i])
        ax.legend()
    else:
        ax.plot(n[i],cost[i])
    return ax

#%%% Entropy Analysis
def Compute_Prob(path, showCount = False):
    """
    Estimate the probabilities of obtaining a 0 or a 1 in the sequence
    based on their observed frequencies. The longer the sequence,
    the higher the confidence in this estimate.

    If showCount=True, this function also displays the difference
    between the number of 0s and 1s.
    """
    zCount = 0
    oCount = 0
    bitCount = 0
    
    try:
        with open(path,"r") as f: # To avoid overflow
            strArr = f.read(readStep)
            currLen = len(strArr)
            while currLen != 0:
                curr_oCount = strArr.count('1')
                oCount += curr_oCount
                zCount += currLen-curr_oCount
                
                bitCount += currLen
                currBit = f.read(readStep)
                currLen = len(currBit)
    except:
        print(f"ERROR: File was not found in path \n {path}")
        return None,None
    if showCount:
        print(f"0s: {zCount} ({zCount*100/bitCount}), 1s: {oCount} ({oCount*100/bitCount}), bits: {bitCount}, diffPer: {(oCount-zCount)/bitCount}")
    # Calculamos las probabilidades
    zProb  = zCount/bitCount
    oProb = 1-zProb
    return zProb,oProb

def Estimate_Hmin(fileName):
    """
    It is sufficient to consider the most probable outcome in the sequence.

    We use the definition

    Hmin = -log(Max(P_i))

    TODO: Determine how to quantify the confidence of the estimate.
    """
    maxP = max(Compute_Prob(fileName))
    return -np.log2(maxP)

def Estimate_H(fileName):
    probs = Compute_Prob(fileName)
    return -probs[0]*np.log2(probs[0]) - probs[1]*np.log2(probs[1])
#%%% Analisis de la complejidad (distintos compresores)
def Estimate_KComplexity(path):
    """
    Estimate_KComplexity:
        Given a file containing bits, evaluate its compression using different algorithms
        (Deflate// Huffman with gzip; Lempel-Ziv-Markov chain with lzip and PPM with pyppmd).
        We consider the Kolmogorov complexity as the length of the maximum achievable compression,
        and also return the deficiency function.
    """
    y = WF.ReadFile(path,readAsBit = True)
    #print("Estimating Kolmogorov_Complexity")
    initLength = len(y)
    deflate = len(gzip.compress(y, compresslevel = 9)) # Huffmann
    lempel = len(lzip.compress_to_buffer(y,level = 9)) # Lempel-Ziv
    PPM = len(ppm.compress(y, max_order = 64)) # PPM. maxorder = 64 es la compresion maxima
    maxComp = min(deflate,lempel,PPM)
    d = initLength - maxComp
    probD = 2**(-d)
    return maxComp,d,probD, probD > epsilon # Si superas epsilon, eres aleatoria
#%%% Calculo de la tasa de generado
def Compute_Creation_Ratio(filePath):
    """
    Compute_Creation_Ratio:
        Given the times stored in the Times folder, calculate
        the average generation time with its error, and then the generation
        rate per bit with its corresponding error.
    """
    times = []
    bits = []
    with open(filePath) as file:
        line = file.readline()
        while line != "":
            sides = line.split(":") # Separo la linea en lado derecho e izquierdo
            times.append(float(sides[1]))
            compData = sides[0].split("--")[1] # Elimino el nombre del computador
            aux = compData.split("-") # Separo en elementos
            bits.append(float(aux[0])*float(aux[1]))
            line = file.readline()
    # Computing the mean values
    times = np.array(times,dtype = float)
    bits = np.array(bits,dtype = int)
    meanTime = np.mean(times)
    std = np.std(times)
    errMean = std/np.sqrt(len(times))
    
    totalBits = np.sum(bits)
    ratio = totalBits/meanTime # Velocidad bits/s
    errRatio = errMean/meanTime * ratio # Error abs
    return ratio,errRatio
#%%% Calculo de la funcion Costo 

def AWS_Cost_Function(nBits,cs,ct,sMax,sMin,nqbits):
    """
    Cost_Function:
        Calculates the cost.
    """
    # It must work between sMin and sMax. For intermediate values of shots, it should be infinite
    #if nBits > nqbits: nqbits = nBits
    nShots = nBits//nqbits
    nShots = np.where(nShots == 0, 1,nShots) # If we are in the case of requesting fewer bits than qubits
    T = nShots//sMax # Count the number of required tasks
    R = nShots%sMax
    rLess_sMin = R < sMin
    # When R < sMin, one additional task is required and the number of shots does not change
    # (it is now compatible by distributing sMax + R between two tasks)
    f = np.where(rLess_sMin,ct*(T+2) + cs*(sMax*T + R),ct*(T+1) + cs*(sMax*T + R)) # The +1 in T is because task 0 is also counted
    f = np.where(nShots < 1, ct + cs*nShots ,f) # Specific case of requesting fewer bits than qubits
    return f

def IBM_Cost_Function(nBits,ratio, cost_perSecond):
    timeNeeded = nBits/ratio 
    return cost_perSecond*timeNeeded

#%%% TEST SEGUNDO ORDEN
def Mix_Sequences(dirPr,dirRef,outDir = "Mix_Sequences/Mixed_IBM"):
    """
    Mix Sequences:Given two bitfiles, we xor both.
    """
    bitsPrArr = WF.Scan_Dir(dirPr)
    bitsRefArr = WF.Scan_Dir(dirRef)
    lenPr = len(bitsPrArr)
    lenRef = len(bitsRefArr)
    minLen = min(lenPr,lenRef)
    for j in tqdm.tqdm(range(minLen)):
        bitsPr = WF.ReadFile(bitsPrArr[j],readAsBit = True)
        bitsRef = WF.ReadFile(bitsRefArr[j],readAsBit = True)
        nPr = len(bitsPr)
        nRef = len(bitsRef)
        nOut = min(nPr,nRef)
        
        bitsOut = np.empty(nOut,dtype = str)
        for i in range(nOut):
            bitsOut[i] = bitsPr[i] ^ bitsRef[i] # ^ es la operacion XOR en bits 
        
        prBaseName = os.path.basename(bitsPrArr[j])
        refBaseName = os.path.basename(bitsRefArr[j])
        
        WF.Write_Bitfiles(outDir, prBaseName+"--"+refBaseName, bitsOut)
    return   

def Compute_Distribution(t,pValues):
    m = len(pValues)
    nPoints = len(t)
    out = np.zeros(nPoints)
    for i in range(nPoints): 
        aux = np.where(pValues <= t[i])
        out[i] = len(aux[0])
    return out/m

def KS_Shen_Test(dirPr,dirMix, outDir = "KS_Results",nPoints = 5000):
    """
    dirPr: Directory containing the sequences from the problem generator
    dirRef: Directory containing the p-values from the reference generator
    nPoints: Number of points used for the discretization of the G distributions
    We run the complete NIST test suite
    """
    K = np.sqrt(-0.5 *np.log2(epsilon/2)) # Second-order test threshold

    tests = [ft.monobit_test,Block_Frequency_Test,rt.run_test, rt.longest_one_block_test,st.spectral_test,aet.approximate_entropy_test,
             cst.cumulative_sums_test,ut.statistical_test,
             Binary_Matrix_Test,ct.linear_complexity_test]

    testsNames = ["Monobit Test","Frequency Within a Block Test", "Run Test", "Longest One Block Test",
                  "Spectral Test", "Approximate Entropy Test", "Cusum Test", "Maurer Test", "Binary Matrix Test",
                  "Linear Complexity Test"]

    #tests = [ft.monobit_test] # Debugging
    #testsNames = ["Monobit Test"]
    # Run tests separately
    nTests = len(tests)

    #%%%% BLOCK I: Information extraction
    # Load the list of paths for each file into memory
    pathPr = WF.Scan_Dir(dirPr)
    pathMix = WF.Scan_Dir(dirMix)

    nPr = len(pathPr)
    nMix = len(pathMix)

    if nPr > nMix:
        minFile = nMix
    else:
        minFile = nPr

    Gpr = np.zeros((nTests,nPoints))
    GMix = np.zeros((nTests,nPoints))
    tMatrix = np.zeros(nTests,dtype = object)

    pr_pValues = np.zeros((nTests,minFile))
    mix_pValues = np.zeros((nTests,minFile))

    KSResults = np.zeros(nTests)
    passArr = np.zeros(nTests,dtype = bool)

    for i in tqdm.tqdm(range(nTests)):     # Calculate KS test by test
        for j in tqdm.tqdm(range(minFile)):
            currMix = WF.ReadFile(pathMix[j])
            currPr = WF.ReadFile(pathPr[j])

            # Run the test
            mix_pValues[i,j] = tests[i](currMix)[0]
            pr_pValues[i,j] = tests[i](currPr)[0]

        # Check the maximum p-value to define the distribution domain
        maxMix = np.max([mix_pValues[i,:],pr_pValues[i,:]])

        # Calculate the distributions
        tMatrix[i] = np.linspace(0,maxMix,nPoints)
        Gpr[i,:] = Compute_Distribution(tMatrix[i],pr_pValues[i,:])
        GMix[i,:] = Compute_Distribution(tMatrix[i],mix_pValues[i,:])

        # Calculate KS distance
        KSResults[i] = np.max(abs(Gpr[i,:]-GMix[i,:]))
        passArr[i] = KSResults[i] < K

    # Handle Random Excursions separately
    print("Running Random Excursions Test...")

    # Random excursions
    nRd = 8 # Random excursions consist of 8 tests
    mixRD = np.zeros((nRd,minFile))
    prRD = np.zeros((nRd,minFile))
    tMatrixRd = np.zeros(nRd, dtype = object)
    KSRD = np.zeros(nRd)
    passRD = np.zeros(nRd,dtype = bool)

    GprRD = np.zeros((nRd,nPoints))
    GMixRD = np.zeros((nRd,nPoints))

    for j in tqdm.tqdm(range(minFile)):
        currMix = WF.ReadFile(pathMix[j])
        currPr = WF.ReadFile(pathPr[j])

        # Run the test
        mixAux = ret.random_excursions_test(currMix) #[(... , pvalue,...), (...)]
        prAux = ret.random_excursions_test(currPr)

        for i in range(nRd):
            mixRD[i,j] = mixAux[i][3]
            prRD[i,j] = prAux[i][3]

    for i in range(nRd):
        # Check the maximum p-value to define the distribution domain
        maxMix = np.max([mixRD[i,:],prRD[i,:]])

        # Calculate the distributions
        tMatrixRd[i] = np.linspace(0,maxMix,nPoints)
        GprRD[i,:] = Compute_Distribution(tMatrixRd[i],prRD[i,:])
        GMixRD[i,:] = Compute_Distribution(tMatrixRd[i],mixRD[i,:])

        # Calculate KS distance
        KSRD[i] = np.max(abs(GprRD[i,:]-GMixRD[i,:]))
        passRD[i] = KSRD[i] < K


    # Variant

    print("Running Random Excursions Variant Test...")

    nVar = 18 # Variant tests consist of 18 tests
    mixVar = np.ones((nVar,minFile))*2 # Initialized to 2 to ignore missing cases
    prVar = np.ones((nVar,minFile))*2
    tMatrixVar = np.zeros(nVar,dtype = object)
    KSVar = np.zeros(nVar)
    passVar = np.zeros(nVar,dtype = bool)

    GprVar = np.zeros((nVar,nPoints))
    GMixVar = np.zeros((nVar,nPoints))

    for j in tqdm.tqdm(range(minFile)):
        currMix = WF.ReadFile(pathMix[j])
        currPr = WF.ReadFile(pathPr[j])

        # Run the test
        mixAux = ret.variant_test(currMix)
        prAux = ret.variant_test(currPr)

        nMix = len(mixAux)
        nPr = len(prAux)

        for mx in range(nMix):
            pos = int(mixAux[mx][0][:-2]) # Remove .0
            if pos > 0:
                index = pos + 8
            else:
                index = pos + 9

            mixVar[index,j] = mixAux[mx][3]

        for pr in range(nPr):
            pos = int(prAux[pr][0][:-2])

            if pos > 0:
                index = pos + 8
            else:
                index = pos + 9

            prVar[index,j] = prAux[pr][3]

    for i in range(nVar):
        # Check the maximum p-value to define the distribution domain
        maxMix = np.max([mixVar[i,:],prVar[i,:]])

        # Calculate the distributions
        tMatrixVar[i] = np.linspace(0,maxMix,nPoints)
        GprVar[i,:] = Compute_Distribution(tMatrixVar[i],prVar[i,:])
        GMixVar[i,:] = Compute_Distribution(tMatrixVar[i],mixVar[i,:])

        # Calculate KS distance
        KSVar[i] = np.max(abs(GprVar[i,:]-GMixVar[i,:]))
        passVar[i] = KSVar[i] < K

    print("Done! Saving Results...")

    # Write distances to a file
    msg = []
    msg.append("SECOND ORDER TESTS RESULTS (Based on KS distance and Shen's proposal)")
    msg.append("Files from directories:")
    msg.append(f"\t RNG: {dirPr}")
    msg.append(f"\t Mixed: {dirMix}")
    msg.append(f"epsilon = {epsilon} --> K = {K}")
    msg.append("")

    msg.append("")

    for i in range(nTests):
        msg.append(f"\t (o) {testsNames[i]}: {KSResults[i]} -- {passArr[i]}")

    # Run Test
    numbersRd = ["-4","-3","-2","-1","+1","+2","+3","+4"]

    msg.append("\t (o) Random Excursions Test:")

    for i in range(8):
        msg.append(f"\t \t {numbersRd[i]}: {KSRD[i]} -- {passRD[i]}")

    # Variant
    numbersVar = ["-9","-8","-7","-6","-5","-4","-3","-2","-1",
               "+1", "+2", "+3", "+4", "+5", "+6", "+7", "+8", "+9"]

    msg.append("\t (o) Random Excursions Variant Test:")

    for i in range(nVar):
        msg.append(f"\t \t {numbersVar[i]}: {KSVar[i]} -- {passVar[i]}")

    WF.Write_Analysis_Files("KS", msg, directory = outDir)

    # Write obtained distributions to a folder
    WF.Write_Distribution_Files(tMatrix, Gpr, testsNames, directory = "KS_Results/Distributions/Pr")
    WF.Write_Distribution_Files(tMatrix, GMix, testsNames, directory = "KS_Results/Distributions/Mixed")

    # Write Run Test distributions
    WF.Write_Distribution_Files(tMatrixRd, GprRD, numbersRd, directory = "KS_Results/Distributions/Pr/Run_Test")
    WF.Write_Distribution_Files(tMatrixRd, GMixRD, numbersRd, directory = "KS_Results/Distributions/Mixed/Run_Test")

    # Write Variant Test distributions
    numbersVar = ["-9","-8","-7","-6","-5","-4","-3","-2","-1",
               "+1", "+2", "+3", "+4", "+5", "+6", "+7", "+8", "+9"]

    WF.Write_Distribution_Files(tMatrixVar,GprVar,numbersVar,directory = "KS_Results/Distributions/Pr/Variant_Test")
    WF.Write_Distribution_Files(tMatrixVar, GMixVar, numbersVar, directory = "KS_Results/Distributions/Mixed/Variant_Test")

    return


#%%% NIST test suite
def Construct_Sol_Message(testName,p,passMsg, nPassed = ""):
    if nPassed != "":
        return f"\t \t \t (o) {testName}: " + str(p) +" -- " +  str(passMsg) + " (" + str(nPassed) + ")" # The case of summaries
    return f"\t \t \t (o) {testName}: " + str(p) +" -- " +  str(passMsg)

def Binary_Matrix_Test(binary_data): # Implemented by Lucas Hernández Bellón
    # As in NIST, we will use M = Q = 32 (32 rows, 32 columns)
    M = 32
    Q = 32
    nData = len(binary_data)
    # Given the data length, find the number of matrices that will be generated
    N = nData//(M**2)
    # Check how many bits are discarded
    # nLeft = nData%(M**2)
    # Build matrices row by row
    #print(len(dataCrop))
    # Counter for each rank range
    rankM = 0
    rankM1 = 0
    rankLessM1 = 0
    for i in range(N):
        auxMatrix = np.zeros((M,Q),dtype = int)
        for j in range(M): # Fill row by row
            for k in range(Q):
                auxMatrix[j,k] = binary_data[M*Q*i + M*j + k]

        # Compute the ranks, classifying them as r = N, r = N-1 and r < N-1
        matrix = bm.BinaryMatrix(auxMatrix,M,Q)
        rank = matrix.compute_rank()
        if rank == M: rankM += 1
        elif rank == M-1: rankM1 += 1
        else: rankLessM1 += 1

    # Compute the test p-value using X^2.
    """
    Note that the theoretical probability values are evaluated with:
        pM ≈ prod_{j = 1}^{∞} (1-2^{-j})
        p(M-1) ≈ 2 pm ...
        and so on. It only works if M = Q > 10.
        Only the first three rank categories are considered. More could be included
        for higher precision, but with sufficiently large M and Q it is not necessary
        (because their values will be < 0.005).
    """
    X2 = (rankM - 0.2888*N)**2/(0.2888*N) + (rankM1 - 0.5776*N)**2/(0.5776*N) + (rankLessM1 - 0.1336*N)**2/(0.13336*N)
    pval = np.exp(-X2/2)
    # Boolean value to check whether the test was passed
    return pval, pval > epsilon

def Block_Frequency_Test(data):
    data_size = len(data) # To select the number of blocks
    """
    Block selection:
        1. They must be larger than 20 bits
        2. There must not be more than 100 blocks
    """
    block_size = max(data_size//99,21)
    n_blocks = data_size//block_size
    return ft.block_frequency(data,block_size = block_size) # According to NIST, the number of blocks should not exceed 100. The reason is unknown

def NIST_Battery(QC,filePath):
    """
    Execute the complete battery of tests programmed by Steve
    on the data from fileName, and save the results in the associated txt file.
    """
    message = ["\t --> NIST Battery Test:"]
    # Data is directly a string. It could store up to 10^9 bits. For larger amounts, bitarray should be used.
    data = WF.ReadFile(filePath)

    #%%%% FREQUENCY IN SEQUENCES TESTS
    message.append("\t \t --> FREQUENCY IN SEQUENCES")

    # Monobit
    p,passMsg = ft.monobit_test(data)
    message.append(Construct_Sol_Message("Monobit_Test", p, passMsg))

    # Within a block
    data_size = len(data) # To select the number of blocks
    """
    Block selection:
        1. They must be larger than 20 bits
        2. There must not be more than 100 blocks
    """
    block_size = max(data_size//99,21)
    n_blocks = data_size//block_size # Only used for the txt message

    p,passMsg = Block_Frequency_Test(data)
    message.append(Construct_Sol_Message(f"Within a Block (used {block_size} bits for each block. Used {n_blocks} blocks)", p, passMsg))

    # runTest
    p,passMsg = rt.run_test(data)
    message.append(Construct_Sol_Message("runTest",p,passMsg))

    # Longest One Block
    p,passMsg = rt.longest_one_block_test(data)
    message.append(Construct_Sol_Message("Longest One Block",p,passMsg))

    # Discrete Fourier Transform (Spectral) Tests
    message.append("\t \t SPECTRAL TESTS")
    p,passMsg = st.spectral_test(data)
    message.append(Construct_Sol_Message("Spectral Test",p,passMsg))

    #%%%% STATISTICAL MECHANICS TESTS
    message.append("\t \t STATISTICAL MECHANICS TESTS")

    # Approximate Entropy Test
    p,passMsg = aet.approximate_entropy_test(data)
    message.append(Construct_Sol_Message("Approximate Entropy Test",p,passMsg))

    # Cusum Test
    p,passMsg = cst.cumulative_sums_test(data)
    message.append(Construct_Sol_Message("Cusum Test",p,passMsg))

    # Random Excursions Test
    result = ret.random_excursions_test(data) # [pos,xVal,xObs, pos_pValue,passed]
    message.append("\t \t \t (o) Random Excursions Test:")
    for i in range(len(result)):
        message.append(f"\t \t \t \t {result[i][0]}: {result[i][3]} -- {result[i][4]}")

    """
    NOTE: FOR SOME REASON, IF THERE ARE NOT AROUND 10^7 BITS, THE VARIANT TEST DOES NOT REACH FROM -9 TO 9
    """

    # Random Excursions Variant Test
    result = ret.variant_test(data)
    message.append("\t \t \t (o) Random Excursions Variant Test:")
    for i in range(len(result)):
        message.append(f"\t \t \t \t {result[i][0]}: {result[i][3]} -- {result[i][4]}")

    #%%%% KOLMOGOROV COMPLEXITY TESTS
    message.append("\t \t KOLMOGOROV COMPLEXITY TEST")

    # Maurer Universal Statistical Test
    p,passMsg = ut.statistical_test(data)
    message.append(Construct_Sol_Message("Universal Maurer Test",p,passMsg))

    # Binary Matrix Tests.
    """
    The Kho part is incomplete. It is necessary to construct the submatrices from the bits
    and check the rank of each submatrix as the test criterion.
    I decided to implement it manually using numpy.
    """
    p,passMsg = Binary_Matrix_Test(data)
    message.append(Construct_Sol_Message("Binary Matrix Test",p,passMsg))

    # Linear Complexity Test
    p,passMsg = ct.linear_complexity_test(data)
    message.append(Construct_Sol_Message("Linear Complexity Test",p,passMsg))

    # Non-Overlapping Tests (Check suspicious sequences) NOT INCLUDED BECAUSE WE DO NOT HAVE SUSPICIOUS SEQUENCES
    # Overlapping Test (SAME)

    #%%%% END MESSAGE
    message.append("--> END NIST BATTERY TEST ----------")
    WF.Write_Analysis_Files(QC,message,showEndMessage=False)
    return

#%% Summarize RESULTS
def Get_Summary_Results(dataDir, outDir="Data_Summary"):
    """
    Get_Mean_Results:
        Given a directory with files with results of all tests, 
        we compute de mean value of the results for a summary.
    """
    dataFiles = WF.Scan_Dir(dataDir)
    for i in tqdm.tqdm(range(len(dataFiles))):
        currFile = dataFiles[i]
        currComp = os.path.basename(currFile).split("_")[0]
        
        #%%% DataLists
        minEntropyList = []
        entropyList = []
        
        maximumComplexityList = []
        DeficiencyFunctionList = []
        ComplexPValueList = []
        ComplexityPValuePassed = 0
        
        monobitList = []
        monobitPassed = 0
        withinList = []
        withinPassed = 0
        runList =[]
        runPassed = 0
        longestList = []
        longestPassed = 0
        
        spectralList = []
        spectralPassed = 0
        
        approxEntList = []
        approxEntPassed = 0
        cusumList = []
        cusumPassed = 0
        
        # Next time I would use a for, this is horrible
        rdExc0 = [] # -4
        rdExc0Passed = 0
        rdExc1 = [] # -3
        rdExc1Passed = 0
        rdExc2 = [] # -2
        rdExc2Passed = 0
        rdExc3 = [] # -1
        rdExc3Passed = 0
        rdExc4 = [] # +1
        rdExc4Passed = 0
        rdExc5 = [] # +2
        rdExc5Passed = 0
        rdExc6 = [] # +3
        rdExc6Passed = 0
        rdExc7 = [] # +4
        rdExc7Passed = 0
        
        varExc0 = [] # -9
        varExc0Passed = 0
        varExc1 = [] # -8
        varExc1Passed = 0
        varExc2 = [] # -7
        varExc2Passed = 0
        varExc3 = [] # -6
        varExc3Passed = 0
        varExc4 = [] # -5
        varExc4Passed = 0
        varExc5 = [] # -4
        varExc5Passed = 0
        varExc6 = [] # -3
        varExc6Passed = 0
        varExc7 = [] # -2
        varExc7Passed = 0
        varExc8 = [] # -1
        varExc8Passed = 0
        varExc9 = [] # +1
        varExc9Passed = 0
        varExc10 = [] # +
        varExc10Passed = 0
        varExc11 = [] # +
        varExc11Passed = 0
        varExc12 = [] # +4
        varExc12Passed = 0
        varExc13 = [] # +5
        varExc13Passed = 0
        varExc14 = [] # +6
        varExc14Passed = 0
        varExc15 = [] # +7
        varExc15Passed = 0
        varExc16 = [] # +8
        varExc16Passed = 0
        varExc17 = [] # +9
        varExc17Passed = 0
        
        maurerList = []
        maurerPassed = 0
        matrixList = []
        matrixPassed = 0
        linearList = []
        linearPassed = 0
        
        #%%% Data reading
        bitEndPos = -5
        with open(currFile,"r") as file:
            print(currFile)
            currLine = file.readline()
            while currLine != "":
                if "Entropy Estimations" in currLine: # First section
                    currLine = file.readline() 
                    aux = float(currLine.split("=")[1][:bitEndPos]) # bits word removed
                    minEntropyList.append(aux) 
                    
                    currLine = file.readline()
                    aux = float(currLine.split("=")[1][:bitEndPos])
                    entropyList.append(aux)
                    
                    # Complexity section
                    file.readline()
                    file.readline() # Line "Complexity Estimations:"
                    
                    currLine = file.readline()
                    aux = float(currLine.split("=")[1][:bitEndPos])
                    maximumComplexityList.append(aux)
                    
                    currLine = file.readline()
                    aux = float(currLine.split("=")[1])

                    DeficiencyFunctionList.append(aux)
                    
                    currLine = file.readline()
                                        
                    aux = float(currLine.split("=")[1])
                    ComplexPValueList.append(aux)
                    
                    currLine = file.readline()
                    if "True" in currLine.split(":")[1]:
                        ComplexityPValuePassed += 1

                    # Tests NIST
                    file.readline()
                    file.readline()
                    file.readline() # Line "FREQUENCY IN SEQUENCES"
                    
                    currLine = file.readline()
                    crop = currLine.split(":")[1].split("--")
                    #print(currLine)
                    aux = float(crop[0])
                    monobitList.append(aux)
                    if "True" in crop[1]: monobitPassed += 1
                    
                    currLine = file.readline()
                    crop = currLine.split(":")[1].split("--")
                    #print(currLine)
                    aux = float(crop[0])
                    withinList.append(aux)
                    if "True" in crop[1]: withinPassed += 1
                    
                    currLine = file.readline()
                    crop = currLine.split(":")[1].split("--")
                    #print(currLine)
                    aux = float(crop[0])
                    runList.append(aux)
                    if "True" in crop[1]: runPassed += 1
                    
                    currLine = file.readline()
                    crop = currLine.split(":")[1].split("--")
                    #print(currLine)
                    aux = float(crop[0])
                    longestList.append(aux)
                    if "True" in crop[1]: longestPassed += 1
                    
                    file.readline() # Linea "Spectral Tests"
                    currLine = file.readline()
                    crop = currLine.split(":")[1].split("--")
                    #print(currLine)
                    aux = float(crop[0])
                    spectralList.append(aux)
                    if "True" in crop[1]: spectralPassed += 1
                    
                    file.readline() # Linea "Statistical Mechanics Tests"
                    currLine = file.readline()
                    crop = currLine.split(":")[1].split("--")
                    #print(currLine)
                    aux = float(crop[0])
                    approxEntList.append(aux)
                    if "True" in crop[1]: approxEntPassed += 1
                    
                    currLine = file.readline()
                    crop = currLine.split(":")[1].split("--")
                    #print(currLine)
                    aux = float(crop[0])
                    cusumList.append(aux)
                    if "True" in crop[1]: cusumPassed += 1
                    
                    # Region Random Excursions
                    file.readline()
                    currLine = file.readline()
                    crop = currLine.split(":")[1].split("--")
                    #print(currLine)
                    aux = float(crop[0])
                    rdExc0.append(aux)
                    if "True" in crop[1]: rdExc0Passed += 1
                    
                    currLine = file.readline()
                    crop = currLine.split(":")[1].split("--")
                    #print(currLine)
                    aux = float(crop[0])
                    rdExc1.append(aux)
                    if "True" in crop[1]: rdExc1Passed += 1
                    
                    currLine = file.readline()
                    crop = currLine.split(":")[1].split("--")
                    #print(currLine)
                    aux = float(crop[0])
                    rdExc2.append(aux)
                    if "True" in crop[1]: rdExc2Passed += 1
                    
                    currLine = file.readline()
                    crop = currLine.split(":")[1].split("--")
                    #print(currLine)
                    aux = float(crop[0])
                    rdExc3.append(aux)
                    if "True" in crop[1]: rdExc3Passed += 1
                    
                    currLine = file.readline()
                    crop = currLine.split(":")[1].split("--")
                    #print(currLine)
                    aux = float(crop[0])
                    rdExc4.append(aux)
                    if "True" in crop[1]: rdExc4Passed += 1
                    
                    currLine = file.readline()
                    crop = currLine.split(":")[1].split("--")
                    #print(currLine)
                    aux = float(crop[0])
                    rdExc5.append(aux)
                    if "True" in crop[1]: rdExc5Passed += 1
                    
                    currLine = file.readline()
                    crop = currLine.split(":")[1].split("--")
                    #print(currLine)
                    aux = float(crop[0])
                    rdExc6.append(aux)
                    if "True" in crop[1]: rdExc6Passed += 1
                    
                    currLine = file.readline()
                    crop = currLine.split(":")[1].split("--")
                    #print(currLine)
                    aux = float(crop[0])
                    rdExc7.append(aux)
                    if "True" in crop[1]: rdExc7Passed += 1

                    # Seccion Variant:
                    file.readline()
                    # Variant test could no reach from -9  to 9, we have to tread with care
                    currLine = file.readline() 
                    if "-9" in currLine: 
                        crop = currLine.split(":")[1].split("--")
                        aux = float(crop[0])
                        varExc0.append(aux)
                        if "True" in crop[1]: varExc0Passed += 1
                        currLine = file.readline()
                    if "-8" in currLine:
                        crop = currLine.split(":")[1].split("--")
                        aux = float(crop[0])
                        varExc1.append(aux)
                        if "True" in crop[1]: varExc1Passed += 1
                        currLine = file.readline()
                    if "-7" in currLine:
                        crop = currLine.split(":")[1].split("--")
                        aux = float(crop[0])
                        if "True" in crop[1]: varExc2Passed += 1
                        varExc2.append(aux)
                    
                        currLine = file.readline()
                    if "-6" in currLine:
                        crop = currLine.split(":")[1].split("--")
                        aux = float(crop[0])
                        varExc3.append(aux)
                        if "True" in crop[1]: varExc3Passed += 1
                        currLine = file.readline()
                    if "-5" in currLine:
                        crop = currLine.split(":")[1].split("--")
                        aux = float(crop[0])
                        varExc4.append(aux)
                        if "True" in crop[1]: varExc4Passed += 1
                        currLine = file.readline()
                    if "-4" in currLine:
                        crop = currLine.split(":")[1].split("--")
                        aux = float(crop[0])
                        varExc5.append(aux)
                        if "True" in crop[1]: varExc5Passed += 1
                        currLine = file.readline()
                    if "-3" in currLine:
                        crop = currLine.split(":")[1].split("--")
                        aux = float(crop[0])
                        varExc6.append(aux)
                        if "True" in crop[1]: varExc6Passed += 1
                        currLine = file.readline()
                    if "-2" in currLine:
                        crop = currLine.split(":")[1].split("--")
                        aux = float(crop[0])
                        varExc7.append(aux)
                        if "True" in crop[1]: varExc7Passed += 1
                        currLine = file.readline()
                    if "-1" in currLine:
                        crop = currLine.split(":")[1].split("--")
                        aux = float(crop[0])
                        varExc8.append(aux)
                        if "True" in crop[1]: varExc8Passed += 1
                        currLine = file.readline()
                    if "+1" in currLine:
                        crop = currLine.split(":")[1].split("--")
                        aux = float(crop[0])
                        varExc9.append(aux)
                        if "True" in crop[1]: varExc9Passed += 1
                        currLine = file.readline()
                    if "+2" in currLine:
                        crop = currLine.split(":")[1].split("--")
                        aux = float(crop[0])
                        varExc10.append(aux)
                        if "True" in crop[1]: varExc10Passed += 1
                        currLine = file.readline()
                    if "+3" in currLine:
                        crop = currLine.split(":")[1].split("--")
                        aux = float(crop[0])
                        varExc11.append(aux)
                        if "True" in crop[1]: varExc11Passed += 1
                        currLine = file.readline()
                    if "+4" in currLine:
                        crop = currLine.split(":")[1].split("--")
                        aux = float(crop[0])
                        varExc12.append(aux)
                        if "True" in crop[1]: varExc12Passed += 1
                        currLine = file.readline()
                    if "+5" in currLine:
                        crop = currLine.split(":")[1].split("--")
                        aux = float(crop[0])
                        varExc13.append(aux)
                        if "True" in crop[1]: varExc13Passed += 1
                        currLine = file.readline()
                    if "+6" in currLine:
                        crop = currLine.split(":")[1].split("--")
                        aux = float(crop[0])
                        varExc14.append(aux)
                        if "True" in crop[1]: varExc14Passed += 1
                        currLine = file.readline()
                    if "+7" in currLine:
                        crop = currLine.split(":")[1].split("--")
                        aux = float(crop[0])
                        varExc15.append(aux)
                        if "True" in crop[1]: varExc15Passed += 1
                        currLine = file.readline()
                    if "+8" in currLine:    
                        crop = currLine.split(":")[1].split("--")
                        aux = float(crop[0])
                        varExc16.append(aux)
                        if "True" in crop[1]: varExc16Passed += 1
                        currLine = file.readline()
                    if "+9" in currLine:
                        crop = currLine.split(":")[1].split("--")
                        aux = float(crop[0])
                        varExc17.append(aux)
                        if "True" in crop[1]: varExc17Passed += 1
                        file.readline() 
                    # Finally the long region has ended
                    
                    # Line "KOLMOGOROV COMPLEXITY TEST"
                    currLine = file.readline()
                    crop = currLine.split(":")[1].split("--")
                    aux = float(crop[0])
                    maurerList.append(aux)
                    if "True" in crop[1]: maurerPassed += 1
                    
                    currLine = file.readline()
                    crop = currLine.split(":")[1].split("--")
                    aux = float(crop[0])
                    matrixList.append(aux)
                    if "True" in crop[1]: matrixPassed += 1
                    
                    currLine = file.readline()
                    crop = currLine.split(":")[1].split("--")
                    aux = float(crop[0])
                    linearList.append(aux)
                    if "True" in crop[1]: linearPassed += 1
                # Next section
                currLine = file.readline()
        #%%% Statistical calculus
        nData = len(entropyList) # number of files
        sqrData = np.sqrt(nData)

        meanMinH = np.mean(minEntropyList)
        errMinH = np.std(minEntropyList)/sqrData
        
        meanH = np.mean(entropyList)
        errH = np.std(minEntropyList)/sqrData
        
        meanMaxComplex = np.mean(maximumComplexityList)
        errMaxComplex = np.std(maximumComplexityList)/sqrData 
        
        meanDeficiency = np.mean(DeficiencyFunctionList)
        errDeficiency = np.std(DeficiencyFunctionList)/sqrData
        
        meanComplexPValue = np.mean(ComplexPValueList)
        errComplexPValue = np.std(ComplexPValueList)/sqrData
        
        meanMonobit = np.mean(monobitList)
        errMonobit = np.std(monobitList)/sqrData
        
        meanWithin = np.mean(withinList)
        errWithin = np.std(withinList)/sqrData
        
        meanRun = np.mean(runList)
        errRun = np.std(runList)/sqrData
        
        meanLongest = np.mean(longestList)
        errLongest = np.std(longestList)/sqrData
        
        meanSpectral = np.mean(spectralList)
        errSpectral = np.std(spectralList)/sqrData
        
        meanApprox = np.mean(approxEntList)
        errApprox = np.std(approxEntList)/sqrData
        
        meanCusum = np.mean(cusumList)
        errCusum = np.std(cusumList)/sqrData
        
        meanRD0 = np.mean(rdExc0)
        errRD0 = np.std(rdExc0)/sqrData
        
        meanRD1 = np.mean(rdExc1)
        errRD1 = np.std(rdExc1)/sqrData
        
        meanRD2 = np.mean(rdExc2)
        errRD2 = np.std(rdExc2)/sqrData
        
        meanRD3 = np.mean(rdExc3)
        errRD3 = np.std(rdExc3)/sqrData
        
        meanRD4 = np.mean(rdExc4)
        errRD4 = np.std(rdExc4)/sqrData
        
        meanRD5 = np.mean(rdExc5)
        errRD5 = np.std(rdExc5)/sqrData
        
        meanRD6 = np.mean(rdExc6)
        errRD6 = np.std(rdExc6)/sqrData
        
        meanRD7 = np.mean(rdExc7)
        errRD7 = np.std(rdExc7)/sqrData
        
        meanVar0 = np.mean(varExc0)
        errVar0 = np.std(varExc0)/sqrData
         
        meanVar1 = np.mean(varExc1)
        errVar1 = np.std(varExc1)/sqrData
        
        meanVar2 = np.mean(varExc2)
        errVar2 = np.std(varExc2)/sqrData
        
        meanVar3 = np.mean(varExc3)
        errVar3 = np.std(varExc3)/sqrData
         
        meanVar4 = np.mean(varExc4)
        errVar4 = np.std(varExc4)/sqrData
        
        meanVar5 = np.mean(varExc5)
        errVar5 = np.std(varExc5)/sqrData
        
        meanVar6 = np.mean(varExc6)
        errVar6 = np.std(varExc6)/sqrData
        
        meanVar7 = np.mean(varExc7)
        errVar7 = np.std(varExc7)/sqrData
        
        meanVar8 = np.mean(varExc8)
        errVar8 = np.std(varExc8)/sqrData
        
        meanVar9 = np.mean(varExc9)
        errVar9 = np.std(varExc9)/sqrData
        
        meanVar10 = np.mean(varExc10)
        errVar10 = np.std(varExc10)/sqrData
        
        meanVar11 = np.mean(varExc11)
        errVar11 = np.std(varExc11)/sqrData
        
        meanVar12 = np.mean(varExc12)
        errVar12 = np.std(varExc12)/sqrData
        
        meanVar13 = np.mean(varExc13)
        errVar13 = np.std(varExc13)/sqrData
        
        meanVar14 = np.mean(varExc14)
        errVar14 = np.std(varExc14)/sqrData
        
        meanVar15 = np.mean(varExc15)
        errVar15 = np.std(varExc15)/sqrData
        
        meanVar16 = np.mean(varExc16)
        errVar16 = np.std(varExc16)/sqrData
        
        meanVar17 = np.mean(varExc17)
        errVar17 = np.std(varExc17)/sqrData
        
        meanMaurer = np.mean(maurerList)
        errMaurer = np.std(maurerList)/sqrData
        
        meanMatrix = np.mean(matrixList)
        errMatrix = np.std(matrixList)/sqrData
        
        meanLinear = np.mean(linearList)
        errLinear = np.std(linearList)/sqrData
        
        #%%% Writing summary
        msg = []
        msg.append(f"{currComp} Data Summary: Used {nData} files. \n '(n)' after Passed Result indicates how many of the files passed that test.")
        
        msg.append("\t--> Entropy Estimations:")
        msg.append(f"\t\t --> H_min = {ufloat(meanMinH,errMinH)} bits")
        msg.append(f"\t\t\t --> Worst H_min = {np.min(minEntropyList)} bits")
        msg.append(f"\t\t --> H = {ufloat(meanH,errH)} bits")
        msg.append(f"\t\t\t --> Worst H = {np.min(entropyList)} bits")
        
        msg = msg + ["\t --> Complexity Estimations:",f"\t\t --> Maximum Complexity = {ufloat(meanMaxComplex,errMaxComplex)} bits", 
                     f"\t \t \t --> Worst Complexity =  {np.min(maximumComplexityList)} bits",
                    f"\t \t --> Deficiency Function = {ufloat(meanDeficiency,errDeficiency)}",
                    f"\t \t\t --> Worst Deficiency Function = {np.max(DeficiencyFunctionList)}",
                    f"\t \t --> p-value = {ufloat(meanComplexPValue,errComplexPValue)} -- {str(meanComplexPValue >= epsilon)} ({ComplexityPValuePassed})",
                    f"\t \t\t --> Worst p-value = {np.min(ComplexPValueList)} --  {np.min(ComplexPValueList) >= epsilon}"]
        
        msg.append("\t --> NIST Battery Test:")
        
        msg.append("\t \t --> FREQUENCY IN SEQUENCES")
        msg.append(Construct_Sol_Message("Monobit_Test", ufloat(meanMonobit,errMonobit), meanMonobit >= epsilon,monobitPassed))
        msg.append(f"\t \t \t \t Worst p-value: {np.min(monobitList)} --  {np.min(monobitList) >= epsilon}")
        msg.append(Construct_Sol_Message("Within a Block", ufloat(meanWithin,errWithin), meanWithin >= epsilon,withinPassed))
        msg.append(f"\t \t \t \t Worst p-value: {np.min(withinList)} --  {np.min(withinList) >= epsilon}")
        msg.append(Construct_Sol_Message("Run Test", ufloat(meanRun,errRun), meanRun >= epsilon,runPassed))
        msg.append(f"\t \t \t \t Worst p-value: {np.min(runList)} --  {np.min(runList) >= epsilon}")
        msg.append(Construct_Sol_Message("Longest One Block",ufloat(meanLongest,errLongest),meanLongest >= epsilon,longestPassed))
        msg.append(f"\t \t \t \t Worst p-value: {np.min(longestList)} --  {np.min(longestList) >= epsilon}")
        
        msg.append("\t \t SPECTRAL TESTS")
        msg.append(Construct_Sol_Message("Spectral Test",ufloat(meanSpectral,errSpectral),meanSpectral >= epsilon,spectralPassed))
        msg.append(f"\t \t \t \t Worst p-value: {np.min(spectralList)} --  {np.min(spectralList) >= epsilon}")
        msg.append("\t \t STATISTICAL MECHANICS TESTS")
        msg.append(Construct_Sol_Message("Approximate Entropy Test",ufloat(meanApprox,errApprox),meanApprox >= epsilon,approxEntPassed))
        msg.append(f"\t \t \t \t Worst p-value: {np.min(approxEntList)} --  {np.min(approxEntList) >= epsilon}")
        msg.append(Construct_Sol_Message("Cusum Test",ufloat(meanCusum,errCusum),meanCusum >= epsilon,cusumPassed))
        msg.append(f"\t \t \t \t Worst p-value: {np.min(cusumList)} --  {np.min(cusumList) >= epsilon}")
        
        msg.append("\t \t \t (o) Random Excursions Test:")
        msg.append(f"\t \t \t \t -4: {ufloat(meanRD0,errRD0)} -- {meanRD0 >= epsilon}  ({rdExc0Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {np.min(rdExc0)} --  {np.min(rdExc0) >= epsilon}")
        msg.append(f"\t \t \t \t -3: {ufloat(meanRD1,errRD1)} -- {meanRD1 >= epsilon} ({rdExc1Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {np.min(rdExc1)} --  {np.min(rdExc1) >= epsilon}")
        msg.append(f"\t \t \t \t -2: {ufloat(meanRD2,errRD2)} -- {meanRD2 >= epsilon}  ({rdExc2Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {np.min(rdExc2)} --  {np.min(rdExc2) >= epsilon}")
        msg.append(f"\t \t \t \t  -1: {ufloat(meanRD3,errRD3)} -- {meanRD3 >= epsilon} ({rdExc3Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {np.min(rdExc3)} --  {np.min(rdExc3) >= epsilon}")
        msg.append(f"\t \t \t \t +1: {ufloat(meanRD4,errRD4)} -- {meanRD4 >= epsilon} ({rdExc4Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {np.min(rdExc4)} --  {np.min(rdExc4) >= epsilon}")
        msg.append(f"\t \t \t \t +2: {ufloat(meanRD5,errRD5)} -- {meanRD5 >= epsilon} ({rdExc5Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {np.min(rdExc5)} --  {np.min(rdExc5) >= epsilon}")
        msg.append(f"\t \t \t \t +3: {ufloat(meanRD6,errRD6)} -- {meanRD6 >= epsilon} ({rdExc6Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {np.min(rdExc6)} --  {np.min(rdExc6) >= epsilon}")
        msg.append(f"\t \t \t \t +4: {ufloat(meanRD7,errRD7)} -- {meanRD7 >= epsilon} ({rdExc7Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {np.min(rdExc7)} --  {np.min(rdExc7) >= epsilon}")
        
        msg.append("\t \t \t (o) Random Excursions Variant Test:")
        msg.append(f"\t \t \t \t -9: {ufloat(meanVar0,errVar0)} -- {meanVar0 >= epsilon} ({varExc0Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {min(varExc0,default = np.nan)} --  {min(varExc0,default = np.nan) >= epsilon}")
        msg.append(f"\t \t \t \t -8: {ufloat(meanVar1,errVar1)} -- {meanVar1 >= epsilon} ({varExc1Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {min(varExc1,default = np.nan)} --  {min(varExc1,default = np.nan) >= epsilon}")
        msg.append(f"\t \t \t \t -7: {ufloat(meanVar2,errVar2)} -- {meanVar2 >= epsilon} ({varExc2Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {min(varExc2,default = np.nan)} --  {min(varExc2,default = np.nan) >= epsilon}")
        msg.append(f"\t \t \t \t -6: {ufloat(meanVar3,errVar3)} -- {meanVar3 >= epsilon} ({varExc3Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {min(varExc3,default = np.nan)} --  {min(varExc3,default = np.nan) >= epsilon}")
        msg.append(f"\t \t \t \t -5: {ufloat(meanVar4,errVar4)} -- {meanVar4 >= epsilon} ({varExc4Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {min(varExc4,default = np.nan)} --  {min(varExc4,default = np.nan) >= epsilon}")
        msg.append(f"\t \t \t \t -4: {ufloat(meanVar5,errVar5)} -- {meanVar5 >= epsilon} ({varExc5Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {min(varExc5,default = np.nan)} --  {min(varExc5,default = np.nan) >= epsilon}")
        msg.append(f"\t \t \t \t -3: {ufloat(meanVar6,errVar6)} -- {meanVar6 >= epsilon} ({varExc6Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {min(varExc6,default = np.nan)} --  {min(varExc6,default = np.nan) >= epsilon}")
        msg.append(f"\t \t \t \t -2: {ufloat(meanVar7,errVar7)} -- {meanVar7 >= epsilon} ({varExc7Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {min(varExc7,default = np.nan)} --  {min(varExc7,default = np.nan) >= epsilon}")
        msg.append(f"\t \t \t \t -1: {ufloat(meanVar8,errVar8)} -- {meanVar8 >= epsilon} ({varExc8Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {min(varExc8,default = np.nan)} --  {min(varExc8,default = np.nan) >= epsilon}")
        msg.append(f"\t \t \t \t +1: {ufloat(meanVar9,errVar9)} -- {meanVar9 >= epsilon} ({varExc9Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {min(varExc9,default = np.nan)} --  {min(varExc9,default = np.nan) >= epsilon}")
        msg.append(f"\t \t \t \t +2: {ufloat(meanVar10,errVar10)} -- {meanVar10 >= epsilon} ({varExc10Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {min(varExc10,default = np.nan)} --  {min(varExc10,default = np.nan) >= epsilon}")
        msg.append(f"\t \t \t \t +3: {ufloat(meanVar11,errVar11)} -- {meanVar11 >= epsilon} ({varExc11Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {min(varExc11,default = np.nan)} --  {min(varExc11,default = np.nan) >= epsilon}")
        msg.append(f"\t \t \t \t +4: {ufloat(meanVar12,errVar12)} -- {meanVar12 >= epsilon} ({varExc12Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {min(varExc12,default = np.nan)} --  {min(varExc12,default = np.nan) >= epsilon}")
        msg.append(f"\t \t \t \t +5: {ufloat(meanVar13,errVar13)} -- {meanVar13 >= epsilon} ({varExc13Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {min(varExc13,default = np.nan)} --  {min(varExc13,default = np.nan) >= epsilon}")
        msg.append(f"\t \t \t \t +6: {ufloat(meanVar14,errVar14)} -- {meanVar14 >= epsilon} ({varExc14Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {min(varExc14,default = np.nan)} --  {min(varExc14,default = np.nan) >= epsilon}")
        msg.append(f"\t \t \t \t +7: {ufloat(meanVar15,errVar15)} -- {meanVar15 >= epsilon} ({varExc15Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {min(varExc15,default = np.nan)} --  {min(varExc15,default = np.nan) >= epsilon}")
        msg.append(f"\t \t \t \t +8: {ufloat(meanVar16,errVar16)} -- {meanVar16 >= epsilon} ({varExc16Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {min(varExc16,default = np.nan)} --  {min(varExc16,default = np.nan) >= epsilon}")
        msg.append(f"\t \t \t \t +9: {ufloat(meanVar17,errVar17)} -- {meanVar17 >= epsilon} ({varExc17Passed})")
        msg.append(f"\t \t \t \t \t Worst p-value: {min(varExc17,default = np.nan)} --  {min(varExc17,default = np.nan) >= epsilon}")
        
        msg.append("\t \t KOLMOGOROV COMPLEXITY TEST")
        msg.append(Construct_Sol_Message("Universal Maurer Test",ufloat(meanMaurer,errMaurer),meanMaurer >= epsilon, maurerPassed))
        msg.append(f"\t \t \t \t Worst p-value: {np.min(maurerList)} --  {np.min(maurerList) >= epsilon}")
        msg.append(Construct_Sol_Message("Binary Matrix Test",ufloat(meanMatrix,errMatrix),meanMatrix >= epsilon,matrixPassed))
        msg.append(f"\t \t \t \t Worst p-value: {np.min(matrixList)} --  {np.min(matrixList) >= epsilon}")
        msg.append(Construct_Sol_Message("Linear Complexity Test",ufloat(meanLinear,errLinear),meanLinear >= epsilon, linearPassed))
        msg.append(f"\t \t \t \t Worst p-value: {np.min(linearList)} --  {np.min(linearList) >= epsilon}")
        
        WF.Write_Analysis_Files(currComp,msg,directory=outDir,showEndMessage=False)
    return
    